CREATE TABLE IF NOT EXISTS cars (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    driver_id BIGINT UNIQUE REFERENCES drivers(user_id) ON DELETE SET NULL,
	mark VARCHAR(32) NOT NULL,
	model VARCHAR(32) NOT NULL,
	car_number VARCHAR(32) UNIQUE NOT NULL CHECK (check_car_number(car_number)),
	class_id BIGINT NOT NULL DEFAULT 1 REFERENCES car_classes(id) ON DELETE SET DEFAULT,
	status_id BIGINT NOT NULL DEFAULT 1 REFERENCES car_statuses(id) ON DELETE SET DEFAULT
)