CREATE TABLE IF NOT EXISTS orders_cancels (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
	canceled_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	comment VARCHAR(255) NOT NULL
)