CREATE TABLE IF NOT EXISTS maintenances (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status_id BIGINT NOT NULL DEFAULT 1 REFERENCES maintenance_statuses(id) ON DELETE SET DEFAULT,
	mechanic_id BIGINT NOT NULL DEFAULT 1 REFERENCES mechanics(user_id) ON DELETE SET DEFAULT,
	car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
	maintenance_start TIMESTAMP NOT NULL,
	maintenance_end TIMESTAMP,
	comment VARCHAR(255) NOT NULL
)