CREATE TABLE IF NOT EXISTS marchrutes (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
	distance DOUBLE PRECISION NOT NULL
)