CREATE TABLE IF NOT EXISTS cars_status_history (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
    status_id BIGINT NOT NULL DEFAULT 1 REFERENCES car_statuses(id) ON DELETE SET DEFAULT,
    changed_at TIMESTAMP NOT NULL DEFAULT now()
)