CREATE TABLE IF NOT EXISTS orders (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status_id BIGINT NOT NULL REFERENCES order_statuses(id) ON DELETE SET DEFAULT,
	client_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    driver_id BIGINT REFERENCES drivers(user_id) ON DELETE SET NULL,
	price DOUBLE PRECISION NOT NULL CHECK (price > 0)
)