CREATE TABLE IF NOT EXISTS payments (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id BIGINT UNIQUE NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
	method_id BIGINT NOT NULL DEFAULT 1 REFERENCES payment_methods(id) ON DELETE SET DEFAULT,
    status_id BIGINT NOT NULL DEFAULT 1 REFERENCES payment_statuses(id) ON DELETE SET DEFAULT,
	price DOUBLE PRECISION NOT NULL CHECK (price > 0)
)