CREATE TABLE IF NOT EXISTS payment_status_history (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    status_id BIGINT NOT NULL DEFAULT 1 REFERENCES payment_statuses(id) ON DELETE SET DEFAULT,
    changed_at TIMESTAMP NOT NULL DEFAULT now()
)