CREATE TABLE IF NOT EXISTS orders_status_history (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    order_status_id BIGINT NOT NULL DEFAULT 1 REFERENCES order_statuses(id) ON DELETE SET DEFAULT,
    changed_at TIMESTAMP NOT NULL DEFAULT now()
)